### PR TITLE
Added Chat Functionality

### PR DESCRIPTION
**Pull request by YashGovekar**
I have implemented chat feature. Please check it from your end as well. 
I hope there are no mistakes in it.

### CODE REVIEW

**Comment by holtwick** [comment]
Thanks a lot! I'm going to review in the next days.

**Comment by holtwick** [comment]
This is a great addition to Briefing and it works well. It would be great, if this feature could be optional. Especially the obligatory dialog asking for the name is a bit disturbing the current flow. So do you think it would be possible to set the name later, when the chat is activated? It would also be great, if a second click on the chat icon would close the chat again. Please not my additions as well. I changed the chat icon (I use these https://feathericons.com/ ) and some formatting.

**Comment by YashGovekar** [comment]
> This is a great addition to Briefing and it works well. It would be great, if this feature could be optional. Especially the obligatory dialog asking for the name is a bit disturbing the current flow. So do you think it would be possible to set the name later, when the chat is activated? It would also be great, if a second click on the chat icon would close the chat again. Please not my additions as well. I changed the chat icon (I use these https://feathericons.com/ ) and some formatting.
> 
> I'm currently working on a chat implementation myself for another project. Technically it is different, therefore I cannot use it for Briefing. But it might be inspiring regarding the functionality: https://viidoo.chat

Hello, you're welcome :)
Yes, I can do as you mentioned for chat and will push the changes.
By the way, is https://viidoo.chat your private project or it's gonna be opensource? 
It looks really awesome. Great work!

**Comment by YashGovekar** [comment]
> This is a great addition to Briefing and it works well. It would be great, if this feature could be optional. Especially the obligatory dialog asking for the name is a bit disturbing the current flow. So do you think it would be possible to set the name later, when the chat is activated? It would also be great, if a second click on the chat icon would close the chat again. Please not my additions as well. I changed the chat icon (I use these https://feathericons.com/ ) and some formatting.
> 
> I'm currently working on a chat implementation myself for another project. Technically it is different, therefore I cannot use it for Briefing. But it might be inspiring regarding the functionality: https://viidoo.chat

Done :D

**Comment by holtwick** [comment]
Wow, that was fast. I'll review soon.

> By the way, is https://viidoo.chat your private project or it's gonna be opensource?
> It looks really awesome. Great work!

The current plan is, that it will partly be a closed and partly be open source. It is mainly a commercial project, but the roadmap is not yet put into stone. Happy you like it.

**Comment by YashGovekar** [comment]
> Wow, that was fast. I'll review soon.
> 
> > By the way, is https://viidoo.chat your private project or it's gonna be opensource?
> > It looks really awesome. Great work!
> 
> The current plan is, that it will partly be a closed and partly be open source. It is mainly a commercial project, but the roadmap is not yet put into stone. Happy you like it.

Haha yeah!
Oh your commerical project plan sounds good.
Great job!
By the way do you have any idea where I can find STUN / TURN servers for a cheap price?

**Comment by holtwick** [comment]
> By the way do you have any idea where I can find STUN / TURN servers for a cheap price?

I run my own for about 3$ per month, see https://github.com/holtwick/briefing/wiki/TURN-&-STUN-Installation I think this is the cheapest way having an own STUN/TURN server ;)

**Comment by YashGovekar** [comment]
> > By the way do you have any idea where I can find STUN / TURN servers for a cheap price?
> 
> I run my own for about 3$ per month, see https://github.com/holtwick/briefing/wiki/TURN-&-STUN-Installation I think this is the cheapest way having an own STUN/TURN server ;)

Great, thanks once again! 😄

**Comment by YashGovekar** [comment]
Done as mentioned! :)

**Comment by holtwick** [comment]
Oh, I wrote the bullet points to the issue 🤦‍♂️

That's perfect. I'll merge now.

Thanks again for your work! @YashGovekar

**Comment by YashGovekar** [comment]
> Oh, I wrote the bullet points to the issue 🤦‍♂️
> 
> That's perfect. I'll merge now.
> 
> Thanks again for your work! @YashGovekar

No problem. Thankyou for your awesome work as well @holtwick :)

**Comment by holtwick** [comment]
FYI I changed some tiny things and published the new version to https://brie.fi/ng

**Comment by YashGovekar** [comment]
> FYI I changed some tiny things and published the new version to https://brie.fi/ng

Looks perfect!

**Pull request merged**
